# Generated by Django 3.0.2 on 2020-08-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xlfile',
            field=models.FileField(default='Docs/no.pdf', upload_to='Docs/'),
        ),
    ]
