# Generated by Django 3.0.2 on 2020-08-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_xlfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='User_Images/no.png', upload_to='User_Images/'),
        ),
    ]
